//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakrLabs.Choice.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollItem
    {
        public PollItem()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public System.Guid PollItemId { get; set; }
        public string ImageUrl { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> PollId { get; set; }
    
        public virtual Poll Poll { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
