//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakrLabs.Choice.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        public Poll()
        {
            this.PollItems = new HashSet<PollItem>();
        }
    
        public System.Guid PollId { get; set; }
        public byte CategoryId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Abused { get; set; }
        public Nullable<System.DateTime> AbusedDate { get; set; }
        public Nullable<bool> Sponsored { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PollItem> PollItems { get; set; }
    }
}
