//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakrLabs.Choice.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public System.Guid RatingId { get; set; }
        public System.Guid PollItemId { get; set; }
        public System.Guid UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
    
        public virtual PollItem PollItem { get; set; }
        public virtual User User { get; set; }
    }
}
