#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Choice.Android.Resource", IsApplication=true)]

namespace Choice.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PicassoSharp.Resource.String.ApplicationName = global::Choice.Android.Resource.String.ApplicationName;
			global::PicassoSharp.Resource.String.Hello = global::Choice.Android.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_fb_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_gplus_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_twitter_bg = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_camera = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_fb = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_gplus = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_twitter = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int layers_fb_button_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int layers_gplus_button_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int layers_twitter_button_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int linearlayout_bg = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070009
			public const int btnFb = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int btnGplus = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int btnSave = 2131165201;
			
			// aapt resource value: 0x7f07000a
			public const int btnTwitter = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int cameraButton1 = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int cameraButton2 = 2131165200;
			
			// aapt resource value: 0x7f070001
			public const int frameLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int frameLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int frameLayout3 = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int imagePager = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int imgChoice1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int imgChoice2 = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int linearLayout1 = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int menu_create = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int menu_list = 2131165204;
			
			// aapt resource value: 0x7f07000d
			public const int relativeLayout1 = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int relativeLayout2 = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int t_bg = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int txtScore1 = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int txtScore2 = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int webView = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BrowserLoginView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChoiceFragment = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoginView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int NewChoiceView = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int choice_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int menu_create = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menu_list = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int AppBaseTheme = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int AppTheme = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int ButtonText = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int PollScore = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
