#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Choice.Android.Resource", IsApplication=true)]

namespace Choice.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			Choice.Core.Resource.String.library_name = Choice.Android.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_camera = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int MyButton = 2131165191;
			
			// aapt resource value: 0x7f07000d
			public const int btnSave = 2131165197;
			
			// aapt resource value: 0x7f07000a
			public const int cameraButton1 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int cameraButton2 = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int frameLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int frameLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int frameLayout3 = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int imgChoice1 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int imgChoice2 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int linearLayout1 = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int menu_create = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int menu_list = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int relativeLayout1 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int relativeLayout2 = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int txtScore1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int txtScore2 = 2131165190;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChoiceFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NewChoiceView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int choice_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int menu_create = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int menu_list = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int PollScore = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
