//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakrLabs.Mobile.App.UI.MA
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int close = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int facebook_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int l1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int l2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int l3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int l4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int l5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int l6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int l7 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int l8 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int login = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int login_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int login_down = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int logout = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logout_button = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logout_down = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int splash_logo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int wheel_animation = 2130837522;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int btnChoosin = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int frameLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int frameLayout2 = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int frameLayout3 = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int imageView1 = 2131099660;
			
			// aapt resource value: 0x7f060002
			public const int imgChoice1 = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int imgChoice2 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int login = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int poll_fragment = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int poll_fragment2 = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int relativeLayout1 = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int relativeLayout2 = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int txtScore1 = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int txtScore2 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int viewFlipper1 = 2131099655;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChoiceFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChooserView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainView = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int PollScore = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
