#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ShakrLabs.Mobile.App.UI.MA.Resource", IsApplication=true)]

namespace ShakrLabs.Mobile.App.UI.MA
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int close = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int facebook_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_camera = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int l1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int l2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int l3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int l4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int l5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int l6 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int l7 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int l8 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int login = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int login_button = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int login_down = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int logout = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int logout_button = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int logout_down = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int splash_logo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int wheel_animation = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int btnChoosin = 2131165199;
			
			// aapt resource value: 0x7f070012
			public const int btnSave = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int cameraButton1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int cameraButton2 = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int frameLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int frameLayout2 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int frameLayout3 = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int imageView1 = 2131165196;
			
			// aapt resource value: 0x7f070002
			public const int imgChoice1 = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int imgChoice2 = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout1 = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int login = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int menu_create = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int menu_list = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int poll_fragment = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int poll_fragment2 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int relativeLayout1 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int relativeLayout2 = 2131165197;
			
			// aapt resource value: 0x7f070003
			public const int txtScore1 = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int txtScore2 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int viewFlipper1 = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChoiceFragment = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChooserView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NewChoiceView = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int choice_activity = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int menu_create = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int menu_list = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int PollScore = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
